### ISSUE TITLE
[BUG] Dropdown and Search do not work

### ISSUE THREAD

**Issue by MoinJulian** [realgolf/web#314]
**Describe the bug**
While I am logged out I can neither open the Search nor the Dropdown Menu

**To Reproduce**

1. Log out
2. Search or Menu

**Expected behavior**
They should both open normally even if the user is logged out.

**Comment by MoinJulian** [comment]
I ge this error when loading a page where I can't open the menu or search:

``
Error handling response: ReferenceError: CssHitsCounter is not defined
    at applyExtendedCss (chrome-extension://bcjchineajlfhdlaonabjhlllhmdlmdc/adguard/adguard-content.js:6419:33)
    at applySelectors (chrome-extension://bcjchineajlfhdlaonabjhlllhmdlmdc/adguard/adguard-content.js:6382:9)
    at processCssAndScriptsResponse (chrome-extension://bcjchineajlfhdlaonabjhlllhmdlmdc/adguard/adguard-content.js:6358:13)
``

``
Uncaught (in promise) Error: Function called outside component initialization
    at b (34.-qfgtI-X.js:1:1157)
    at J (34.-qfgtI-X.js:1:1322)
    at 0.EAJ-EjL7.js:1:14379
    at x (34.-qfgtI-X.js:1:101)
    at Array.map (<anonymous>)
    at index.5qTYFOhI.js:4:2079
    at M (34.-qfgtI-X.js:1:1780)
``

``
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at os (0.EAJ-EjL7.js:1:14624)
    at 0.EAJ-EjL7.js:1:18438
    at M (34.-qfgtI-X.js:1:1780)
    at ue (index.5qTYFOhI.js:4:3170)
    at new ae (app.w6UUwz85.js:1:5078)
    at ne (entry.OVNMX33i.js:1:11205)
    at Xe (entry.OVNMX33i.js:1:24976)
    at async Module.en (entry.OVNMX33i.js:1:9944)
``

**Comment by MoinJulian** [comment]
The first issue if caused by an extension and has to be ignored
